services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: booklet_backend_app
        ports:
            - 9088:9088
        volumes:
            - ./package.json:/backend/package.json
            - ./tsconfig.json:/backend/tsconfig.json
            - ./.mocharc.json:/backend/.mocharc.json
            - ./tsoa.json:/backend/tsoa.json
            - ./src:/backend/src
        environment:
            ENV: development
            PORT: 9088
            REDIS_HOST: backend_cache
            REDIS_PORT: 6379
            APP_NAME: Booklet Development
            DB_SECRET_NAME: dev-postgres-creds
            JWT_SECRET_NAME: dev-jwt-creds
            PASSWORD_SECRET_NAME: dev-password-creds
            GOOGLE_SERVICE_ACCOUNT: "lateral-medium-358108"

        depends_on:
            backend_cache:
                condition: service_healthy
        command: bash -c 'pnpm build && pnpm test'
        networks:
            - backend_net

    #Redis-cluster
    backend_cache:
        container_name: booklet_backend_cache
        image: redis:8.0.1-alpine
        ports:
            - 6370:6370
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6370
        networks:
            - backend_net

networks:
    backend_net:
        driver: bridge

volumes:
    vault-data:
    grafana-storage:
